export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ background: "lightblue", padding: "1rem" }}>
          <h1>Header</h1>
        </header>
        {children}
        <footer style={{ background: "ghostwhite", padding: "1rem" }}>
          <h2>Footer</h2>
        </footer>
      </body>
    </html>
  );
}
